<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QNMN576" failures="1" tests="7" name="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" time="13.463" errors="0" timestamp="2022-09-10T14:42:54 IST" skipped="6">
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="5.596">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.259">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.251">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.408">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.289">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure.LaunchApp(TestNGListenerDemoForRetryOnTestFailure.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.349">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
  <testcase classname="seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure" name="LaunchApp" time="1.311">
    <skipped/>
  </testcase> <!-- LaunchApp -->
  <system-out/>
</testsuite> <!-- seleniumConcepts.miscellaneousTopics.TestNGListenerDemoForRetryOnTestFailure -->
